Fix new gcc warnings: torch/csrc/jit/runtime/register_ops_utils.h
In file included from /home/user/pytorch/torch/csrc/jit/runtime/register_prim_ops.cpp:7:
/home/user/pytorch/torch/csrc/jit/runtime/register_ops_utils.h: In instantiation of ‘void torch::jit::listContains(Stack&) [with T = std::__cxx11::basic_string<char>; Stack = std::vector<c10::IValue>]’:
/home/user/pytorch/torch/csrc/jit/runtime/register_prim_ops.cpp:1082:34:   required from here
 1082 |         aliasAnalysisFromSchema()),
      |                                  ^
/home/user/pytorch/torch/csrc/jit/runtime/register_ops_utils.h:332:17: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  332 |   for (const T& item : list) {
      |                 ^~~~
/home/user/pytorch/torch/csrc/jit/runtime/register_ops_utils.h:332:3: note: the temporary was destroyed at the end of the full expression ‘__for_begin .c10::impl::ListIterator<std::__cxx11::basic_string<char>, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::operator*().c10::impl::ListElementReference<std::__cxx11::basic_string<char>, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::operator std::conditional_t<true, const std::__cxx11::basic_string<char>&, std::__cxx11::basic_string<char> >()’
  332 |   for (const T& item : list) {
      |   ^~~